export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    // popular
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
    POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
    POPULAR_LOAD_MORE__SUCCESS:'POPULAR_LOAD_MORE__SUCCESS',
    POPULAR_LOAD_MORE__FAIL: 'POPULAR_LOAD_MORE__FAIL',
    // trending
    TRENDING_REFRESH: 'TRENDING_REFRESH',
    TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
    TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
    TRENDING_LOAD_MORE__SUCCESS:'TRENDING_LOAD_MORE__SUCCESS',
    TRENDING_LOAD_MORE__FAIL: 'TRENDING_LOAD_MORE__FAIL'
};

